### ISSUE TITLE
Peer review 1

### ISSUE THREAD

**Issue by hupijekku** [emsknock/binder#1]
# Peer review
Repository cloned: 2020-10-02 at ~22:00  
(Commit 63b3cf293bbb245c204d0180cc99bf9cb3a10cfe)

## Preface
I'm not sure whether this was supposed to be written in finnish or english, but since the project language seems to be english, I'm sticking to that.  
I also have to point out that I have never used Typescript, so reviewing the code logic might be quite difficult for me, but I'll try my best.  

## Overview
The code in general seems to be very readable and well commented.  
There doesn't seem to be any runnable script yet for me to try out (tried npm start based on my knowledge of Node), and the user guide document didn't help as it is empty at the moment of writing this.  
Running tests however worked fine, although as I had to do this peer review on my Windows-laptop, I had to remove the 'clear' from the test script.  
Speaking of tests, the overall coverage is excellent for the files that have tests. The recently added LZW-inflator still seems to be missing them.  

## Code
Based on my minor knowledge of Huffman coding, the project seems to be on the right track. As I wrote in the overview, the code is well commented, the variable naming is consistent and descriptive most of the time, and the function lengths are kept well in check.  
Although it is quite clear from the context what is meant, some variable names such as 'l', 'r' and 'accu' for example in _compressors/huffman/index.ts_ could be written out to keep the code more readable for people not familiar with the algorithm or tree structures.  

## Tests
As I wrote in overview, the test coverage is good, and the tests seem to be testing for things actually relevant to the algorithms.  
This is very trivial, but as I'd like to say something that can be improved, some of the tests could be more specific, and named accordingly.  
For example in _structures/array-list/array-list.test.ts_, instead of tests named like "x works", such as "safe getter works", you could name them more descriptively e.g. "safe getter returns second parameter when out of bounds"

**Comment by emsknock** [comment]
Thank you for the thorough assessment! It was very clear and you gave actionable advice.

I'll clear up, just in case you were left wondering, that the program is indeed not-executable as of now. Running `npm start` would be the way to execute it if it were.

---

* I will remove the `clear` command from the test script — I didn't remember Windows had a different command for clearing the terminal when writing it. And come to think of it, the test script shouldn't do that in the first place.
* I'll clarify the meaning of `l` and `r` in the `HuffmanNode` interface declaration comments by spelling out "left" and "right" there and rename them to `lChild` and `rChild`. I won't change the name of `accu`, however, as I feel that is a sensible shorthand for "accumulator", which in turn is the standard term used with JS's `Array.prototype.reduce`. Any capable code editor will show the documentation for `reduce` when hovered.
* The "x works" titles are definitely way too vague — they will be changed according to your suggestion.
